# Generated by Django 5.1.4 on 2026-04-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_reservation_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('confirmed', 'مؤكدة'), ('cancelled', 'ملغية')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'trip_reservations',
                'ordering': ['-trip_reservation_date'],
            },
        ),
    ]
