# Generated by Django 5.1.4 on 2026-04-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('students', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreservation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='students.student'),
        ),
        migrations.AddField(
            model_name='tripreservation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trips.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='tripreservation',
            unique_together={('student', 'trip')},
        ),
    ]
