# Generated by Django 5.1.4 on 2026-04-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'نشطة'), ('completed', 'مكتملة'), ('cancelled', 'ملغية')], default='pending', max_length=20)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='buses.bus')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='routes.place')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='routes.schedule')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-trip_date', 'schedule__schedule_time'],
            },
        ),
    ]
