# Generated by Django 5.1.4 on 2026-04-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, choices=[('1', 'المستوى 1'), ('2', 'المستوى 2'), ('3', 'المستوى 3'), ('4', 'المستوى 4'), ('5', 'المستوى 5'), ('6', 'المستوى 6'), ('7', 'المستوى 7'), ('8', 'المستوى 8')], max_length=2)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'universities',
                'ordering': ['name'],
            },
        ),
    ]
