# Generated by Django 5.1.4 on 2026-04-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trip_reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.tripreservation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymenttype'),
        ),
    ]
