# Generated by Django 5.1.4 on 2026-04-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('photo_path', models.ImageField(blank=True, null=True, upload_to='buses/')),
            ],
            options={
                'db_table': 'buses',
                'ordering': ['plate_number'],
            },
        ),
    ]
